bert_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
cnhubert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
device: cpu
domain: webtts
env: test
frp: 0
frp_domain: https://webtts.berstar.cn
hz: 32000
is_half: true
keep_wav: false
model_dir: models
open_browser: false
play: false
play_device: 3
public: 0
server_host: 0.0.0.0
server_port: 8080
speaker: {}
tmp_dir: ./AIDubAudio
topmost: false
